name: coverage
on: [push]

jobs:
  couverture:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4  
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install coverage 
      - name: run coverage
        run: |    
          coverage run -m pytes.
