name: isort
on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4  
      - name: Install dependencies
        run: |
          pip install toml pytest
          python -m pip install --upgrade pip 
      - name: run isort
        run: |    
          python3 -e isort .
